// Generated by DesignAssets
// Do not edit this file manually
// Generated on: 2025-09-14 00:07:00 +0000

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif
#if canImport(UIKit)
import UIKit
#endif

// MARK: - DesignAssets

public struct DesignAssets {
    public static let bundle = Bundle.module
    
    // MARK: - Icon Access
    
    @available(iOS 13.0, macOS 10.15, *)
    public static func icon(named name: String) -> Image? {
        #if canImport(SwiftUI)
        return Image(name, bundle: bundle)
        #else
        return nil
        #endif
    }
    
    public static func uiImage(named name: String) -> Any? {
        #if canImport(UIKit)
        return UIImage(named: name, in: bundle, compatibleWith: nil)
        #else
        return nil
        #endif
    }
}

// MARK: - IconName Enum

public extension DesignAssets {
    enum IconName: String, CaseIterable {
        // Social media icons (negative variants)
        case appleNegative = "apple_negative"
        case clubhouseNegative = "clubhouse_negative"
        case discordNegative = "discord_negative"
        case dribbbleNegative = "dribbble_negative"
        case facebookNegative = "facebook_negative"
        case figmaNegative = "figma_negative"
        case githubNegative = "github_negative"
        case googleNegative = "google_negative"
        case instagramNegative = "instagram_negative"
        case linkedinNegative = "linkedin_negative"
        case mediumNegative = "medium_negative"
        case messengerNegative = "messenger_negative"
        case pinterestNegative = "pinterest_negative"
        case redditNegative = "reddit_negative"
        case signalNegative = "signal_negative"
        case snapchatNegative = "snapchat_negative"
        case spotifyNegative = "spotify_negative"
        case telegramNegative = "telegram_negative"
        case threadsNegative = "threads_negative"
        case tiktokNegative = "tiktok_negative"
        case tumblrNegative = "tumblr_negative"
        case twitchNegative = "twitch_negative"
        case vkNegative = "vk_negative"
        case whatsappNegative = "whatsapp_negative"
        case xTwitterNegative = "x_(twitter)_negative"
        case youtubeNegative = "youtube_negative"
        
        // Social media icons (original variants)
        case appleOriginal = "apple_original"
        case clubhouseOriginal = "clubhouse_original"
        case discordOriginal = "discord_original"
        case dribbbleOriginal = "dribbble_original"
        case facebookOriginal = "facebook_original"
        case figmaOriginal = "figma_original"
        case githubOriginal = "github_original"
        case googleOriginal = "google_original"
        case instagramOriginal = "instagram_original"
        case linkedinOriginal = "linkedin_original"
        case mediumOriginal = "medium_original"
        case messengerOriginal = "messenger_original"
        case pinterestOriginal = "pinterest_original"
        case redditOriginal = "reddit_original"
        case signalOriginal = "signal_original"
        case snapchatOriginal = "snapchat_original"
        case spotifyOriginal = "spotify_original"
        case telegramOriginal = "telegram_original"
        case threadsOriginal = "threads_original"
        case tiktokOriginal = "tiktok_original"
        case tumblrOriginal = "tumblr_original"
        case twitchOriginal = "twitch_original"
        case vkOriginal = "vk_original"
        case whatsappOriginal = "whatsapp_original"
        case xTwitterOriginal = "x_(twitter)_original"
        case youtubeOriginal = "youtube_original"
        
        @available(iOS 13.0, macOS 10.15, *)
        public var image: Image? {
            return DesignAssets.icon(named: self.rawValue)
        }
        
        public var uiImage: Any? {
            return DesignAssets.uiImage(named: self.rawValue)
        }
    }
}
