// Generated by DesignAssets
// Do not edit this file manually
// Generated on: 1757798071.0421627

import Foundation
import SwiftUI

#if canImport(UIKit)
import UIKit
#endif

// MARK: - Social Media Icons

public enum SocialMediaIcons {
    public static let version = "1.0.0"
    public static let generatedAt = "\(Date())"
    
    // MARK: - Icon Categories
    
    public enum Instagram {
        /// Instagram Blue social media icon
        public static let blue = SocialIconInfo(
            name: "social_instagram_blue",
            platform: "Instagram",
            color: "Blue",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:456&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
        /// Instagram White social media icon
        public static let white = SocialIconInfo(
            name: "social_instagram_white",
            platform: "Instagram",
            color: "White",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:718&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
    }

    public enum Facebook {
        /// Facebook Blue social media icon
        public static let blue = SocialIconInfo(
            name: "social_facebook_blue",
            platform: "Facebook",
            color: "Blue",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:260&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
        /// Facebook White social media icon
        public static let white = SocialIconInfo(
            name: "social_facebook_white",
            platform: "Facebook",
            color: "White",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:874&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
    }

    public enum Twitter {
        /// Twitter Blue social media icon
        public static let blue = SocialIconInfo(
            name: "social_twitter_blue",
            platform: "Twitter",
            color: "Blue",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:523&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
        /// Twitter White social media icon
        public static let white = SocialIconInfo(
            name: "social_twitter_white",
            platform: "Twitter",
            color: "White",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:891&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
    }

    public enum LinkedIn {
        /// LinkedIn Blue social media icon
        public static let blue = SocialIconInfo(
            name: "social_linkedin_blue",
            platform: "LinkedIn",
            color: "Blue",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:634&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
        /// LinkedIn White social media icon
        public static let white = SocialIconInfo(
            name: "social_linkedin_white",
            platform: "LinkedIn",
            color: "White",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:745&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
    }

    public enum YouTube {
        /// YouTube Red social media icon
        public static let red = SocialIconInfo(
            name: "social_youtube_red",
            platform: "YouTube",
            color: "Red",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:412&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
        /// YouTube White social media icon
        public static let white = SocialIconInfo(
            name: "social_youtube_white",
            platform: "YouTube",
            color: "White",
            figmaUrl: "https://www.figma.com/design/p8IPbfKjR8KAKN4XqjvSVo/Social-Media-Icons--Community-?node-id=I1:567&p=f&t=z6G6nCOsSbnkQLss-0",
            size: 24.0
        )
    }

    // MARK: - All Icons
    public static let allIcons: [SocialIconInfo] = [
        Instagram.blue, Instagram.white,
        Facebook.blue, Facebook.white,
        Twitter.blue, Twitter.white,
        LinkedIn.blue, LinkedIn.white,
        YouTube.red, YouTube.white
    ]

    // MARK: - Platform Collections
    public static let instagramIcons: [SocialIconInfo] = [Instagram.blue, Instagram.white]
    public static let facebookIcons: [SocialIconInfo] = [Facebook.blue, Facebook.white]
    public static let twitterIcons: [SocialIconInfo] = [Twitter.blue, Twitter.white]
    public static let linkedinIcons: [SocialIconInfo] = [LinkedIn.blue, LinkedIn.white]
    public static let youtubeIcons: [SocialIconInfo] = [YouTube.red, YouTube.white]
}

// MARK: - Social Icon Info

public struct SocialIconInfo {
    public let name: String
    public let platform: String
    public let color: String
    public let figmaUrl: String
    public let size: CGFloat
    
    public init(name: String, platform: String, color: String, figmaUrl: String, size: CGFloat) {
        self.name = name
        self.platform = platform
        self.color = color
        self.figmaUrl = figmaUrl
        self.size = size
    }
    
    // MARK: - UIKit Support
    #if canImport(UIKit)
    public var uiImage: UIImage? {
        return UIImage(named: name)?.withRenderingMode(.alwaysOriginal)
    }
    #endif
    
    // MARK: - SwiftUI Support
    public var image: AnyView {
        return AnyView(
            Image(name)
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(width: size, height: size)
        )
    }
    
    // MARK: - Convenience Methods
    public var displayName: String {
        return "\(platform) \(color)"
    }
    
    public var isDarkVariant: Bool {
        return color.lowercased().contains("dark") || color.lowercased().contains("black")
    }
    
    public var isLightVariant: Bool {
        return color.lowercased().contains("light") || color.lowercased().contains("white")
    }
}

// MARK: - Extensions

extension SocialMediaIcons {
    /// Get all icons for a specific platform
    public static func icons(for platform: String) -> [SocialIconInfo] {
        return allIcons.filter { $0.platform.lowercased() == platform.lowercased() }
    }
    
    /// Get all color variants for a specific platform
    public static func colorVariants(for platform: String) -> [String] {
        return Set(icons(for: platform).map { $0.color }).sorted()
    }
    
    /// Get all available platforms
    public static var availablePlatforms: [String] {
        return Set(allIcons.map { $0.platform }).sorted()
    }
}
