// Generated by Figma Integration
// Generated on: 2025-09-25 14:04:33 +0000

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif

public enum GeneratedIcons {
        case check_default_32 // General - default
    case search_default_32 // General - default
    case light_bulb_filled_32 // General - filled
    case outdoor_terrace_default_32 // General - default
    case voice_default_32 // General - default
    case kiosk_filled_32 // General - filled
    case accessibility_filled_32 // General - filled
    case status_info_12 // Status - original
    case status_blocker_20 // Status - original
    case address_default_32 // General - default
    case blocker_default_32 // General - default
    case refresh_filled_32 // General - filled
    case nav_list_default_32 // Navigation - default
    case pause_default // General - default
    case add_default_32 // General - default
    case payment_filled_32 // General - filled
    case status_info_20 // Status - original
    case chevron_down_default_32 // General - default
    case location_no_mobile_order_32 // Map - original
    case delivery_instructions_default_32 // General - default
    case find_me_ios_filled_32 // General - filled
    case meal_filled_32 // General - filled
    case address_filled_32 // General - filled
    case hide_default_32 // General - default
    case keypad_default_32 // General - default
    case map_default_32 // Map - default
    case transactions_default_32 // General - default
    case light_off_bulb_default_32 // General - default
    case status_selected_12 // Status - original
    case list_default_32 // General - default
    case status_success_16 // Status - original
    case light_off_bulb_filled_32 // General - filled
    case full_screen_default_32 // General - default
    case accessibility_default_32 // General - default
    case play_default // General - default
    case minimize_full_screen_default_32 // General - default
    case payment_default_32 // General - default
    case deprecated__chevron_up_filled_32 // General - filled
    case status_alert_20 // Status - original
    case alert_default_32 // Status - default
    case drive_thru_default_32 // General - default
    case chevron_left_default_32 // General - default
    case log_out_default_32 // General - default
    case wi_fi_default_32 // General - default
    case status_info_16 // Status - original
    case status_alert_12 // Status - original
    case status_selected_20 // Status - original
    case refresh_default_32 // General - default
    case curbside_default_32 // General - default
    case pause_filled // General - filled
    case cold_kiosk_filled_32 // General - filled
    case arrow_left_default_32 // General - default
    case restaurant_filled_32 // General - filled
    case delivery_instructions_alt2_default_32 // General - default
    case eat_in_default_32 // General - default
    case light_bulb_default_32 // General - default
    case deprecated_status_alert_12_old // Status - original
    case keypad_filled_32 // General - filled
    case phone_alt2_filled_32 // General - filled
    case link_directions_16 // General - original
    case deprecated__external_link_filled_32 // General - filled
    case bag_default_32 // General - default
    case copy_default_32 // General - default
    case status_selected_16 // Status - original
    case trash_default_32 // General - default
    case eat_in_filled_32 // General - filled
    case search_filled_32 // General - filled
    case deprecated__chevron_down_filled_32 // General - filled
    case wi_fi_filled_32 // General - filled
    case arrow_right_default_32 // General - default
    case walk_thru_filled_32 // General - filled
    case time_filled_32 // General - filled
    case walk_thru_default_32 // General - default
    case alert_filled_32 // Status - filled
    case find_me_ios_no_permission_32 // General - original
    case calendar_filled_32 // General - filled
    case status_success_12 // Status - original
    case mccafe_filled_32 // General - filled
    case counter_default_32 // General - default
    case leave_at_door_default_32 // General - default
    case flash_default_32 // General - default
    case restaurant_default_32 // General - default
    case leave_at_door_filled_32 // General - filled
    case order_delivery_disabled_32 // General - original
    case status_success_20 // Status - original
    case meet_outside_filled_32 // General - filled
    case find_me_android_no_permission_32 // General - original
    case meet_outside_default_32 // General - default
    case charging_filled_32 // General - filled
    case status_check // Status - original
    case order_location_green_32 // Map - original
    case hide_filled_32 // General - filled
    case drive_thru_filled_32 // General - filled
    case recurring_default_32 // General - default
    case order_location_32 // Map - original
    case deprecated__remove_filled_32 // General - filled
    case mccafe_default_32 // General - default
    case deprecated__arrow_right_filled_32 // General - filled
    case play_filled // General - filled
    case qr_code_filled_32 // General - filled
    case deprecated__add_filled_32 // General - filled
    case remove_default_32 // General - default
    case find_me_android_default_32 // General - default
    case charging_default_32 // General - default
    case qr_code_default_32 // General - default
    case voice_filled_32 // General - filled
    case status_false_20v2 // Status - original
    case show_default_32 // General - default
    case edit_filled_32 // General - filled
    case blocker_filled_32 // General - filled
    case language_default_32 // General - default
    case chevron_up_default_32 // General - default
    case deprecated_status_alert_20_old // Status - original
    case meal_default_32 // General - default
    case bag_filled_32 // General - filled
    case link_external_link_16 // General - original
    case arrow_up_left_default_32 // General - default
    case deprecated_chevron_right_filled_32 // General - filled
    case chevron_right_default_32 // General - default
    case kiosk_default_32 // General - default
    case show_filled_32 // General - filled
    case status_alert_16 // Status - original
    case counter_filled_32 // General - filled
    case meet_at_door_filled_32 // General - filled
    case table_service_default_32 // General - default
    case check_filled_32 // General - filled
    case recents_default_32 // General - default
    case flash_filled_32 // General - filled
    case outdoor_terrace_filled_32 // General - filled
    case list_search_default_32 // General - default
    case time_default_32 // General - default
    case timer_default_32 // General - default
    case playground_default_32 // General - default
    case link_arrow // General - original
    case playground_filled_32 // General - filled
    case ios_back // General - original
    case cold_kiosk_default_32 // General - default
    case find_me_ios_default_32 // General - default
    case order_delivery_32 // General - original
    case calendar_default_32 // General - default
    case transactions_filled_32 // General - filled
    case phone_alt2_default_32 // General - default
    case list_filled_32 // General - filled
    case filter_active_32 // General - original
    case find_me_android_filled_32 // General - filled
    case recurring_filled_32 // General - filled
    case meet_at_door_default_32 // General - default
    case close_default_32 // General - default
    case language_filled_32 // General - filled
    case bar_code_default_32 // General - default
    case bar_code_filled_32 // General - filled
    case deprecated__hamburger_filled_32 // General - filled
    case log_out_filled_32 // General - filled
    case deprecated_status_alert_16_old // Status - original
    case status_blocker_12 // Status - original
    case delivery_instructions_alt2_filled_32 // General - filled
    case map_filled_32 // Map - filled
    case table_service_filled_32 // General - filled
    case external_link_default_32 // General - default
    case edit_default_32 // General - default
    case deprecated_chevron_left_filled_32 // General - filled
    case deprecated__close_filled_32 // General - filled
    case curbside_filled_32 // General - filled
    case recents_filled_32 // General - filled
    case status_blocker_16 // Status - original
    case directions_default_32 // General - default
    case deprecated__nav_list_filled_32 // Navigation - filled
    case delivery_instructions_filled_32 // General - filled
    case hamburger_default_32 // General - default
    
    public var imageName: String {
        switch self {
                case .check_default_32: return "check_default_32"
        case .search_default_32: return "search_default_32"
        case .light_bulb_filled_32: return "light_bulb_filled_32"
        case .outdoor_terrace_default_32: return "outdoor_terrace_default_32"
        case .voice_default_32: return "voice_default_32"
        case .kiosk_filled_32: return "kiosk_filled_32"
        case .accessibility_filled_32: return "accessibility_filled_32"
        case .status_info_12: return "status_info_12"
        case .status_blocker_20: return "status_blocker_20"
        case .address_default_32: return "address_default_32"
        case .blocker_default_32: return "blocker_default_32"
        case .refresh_filled_32: return "refresh_filled_32"
        case .nav_list_default_32: return "nav_list_default_32"
        case .pause_default: return "pause_default"
        case .add_default_32: return "add_default_32"
        case .payment_filled_32: return "payment_filled_32"
        case .status_info_20: return "status_info_20"
        case .chevron_down_default_32: return "chevron_down_default_32"
        case .location_no_mobile_order_32: return "location_no_mobile_order_32"
        case .delivery_instructions_default_32: return "delivery_instructions_default_32"
        case .find_me_ios_filled_32: return "find_me_ios_filled_32"
        case .meal_filled_32: return "meal_filled_32"
        case .address_filled_32: return "address_filled_32"
        case .hide_default_32: return "hide_default_32"
        case .keypad_default_32: return "keypad_default_32"
        case .map_default_32: return "map_default_32"
        case .transactions_default_32: return "transactions_default_32"
        case .light_off_bulb_default_32: return "light_off_bulb_default_32"
        case .status_selected_12: return "status_selected_12"
        case .list_default_32: return "list_default_32"
        case .status_success_16: return "status_success_16"
        case .light_off_bulb_filled_32: return "light_off_bulb_filled_32"
        case .full_screen_default_32: return "full_screen_default_32"
        case .accessibility_default_32: return "accessibility_default_32"
        case .play_default: return "play_default"
        case .minimize_full_screen_default_32: return "minimize_full_screen_default_32"
        case .payment_default_32: return "payment_default_32"
        case .deprecated__chevron_up_filled_32: return "deprecated__chevron_up_filled_32"
        case .status_alert_20: return "status_alert_20"
        case .alert_default_32: return "alert_default_32"
        case .drive_thru_default_32: return "drive_thru_default_32"
        case .chevron_left_default_32: return "chevron_left_default_32"
        case .log_out_default_32: return "log_out_default_32"
        case .wi_fi_default_32: return "wi_fi_default_32"
        case .status_info_16: return "status_info_16"
        case .status_alert_12: return "status_alert_12"
        case .status_selected_20: return "status_selected_20"
        case .refresh_default_32: return "refresh_default_32"
        case .curbside_default_32: return "curbside_default_32"
        case .pause_filled: return "pause_filled"
        case .cold_kiosk_filled_32: return "cold_kiosk_filled_32"
        case .arrow_left_default_32: return "arrow_left_default_32"
        case .restaurant_filled_32: return "restaurant_filled_32"
        case .delivery_instructions_alt2_default_32: return "delivery_instructions_alt2_default_32"
        case .eat_in_default_32: return "eat_in_default_32"
        case .light_bulb_default_32: return "light_bulb_default_32"
        case .deprecated_status_alert_12_old: return "deprecated_status_alert_12_old"
        case .keypad_filled_32: return "keypad_filled_32"
        case .phone_alt2_filled_32: return "phone_alt2_filled_32"
        case .link_directions_16: return "link_directions_16"
        case .deprecated__external_link_filled_32: return "deprecated__external_link_filled_32"
        case .bag_default_32: return "bag_default_32"
        case .copy_default_32: return "copy_default_32"
        case .status_selected_16: return "status_selected_16"
        case .trash_default_32: return "trash_default_32"
        case .eat_in_filled_32: return "eat_in_filled_32"
        case .search_filled_32: return "search_filled_32"
        case .deprecated__chevron_down_filled_32: return "deprecated__chevron_down_filled_32"
        case .wi_fi_filled_32: return "wi_fi_filled_32"
        case .arrow_right_default_32: return "arrow_right_default_32"
        case .walk_thru_filled_32: return "walk_thru_filled_32"
        case .time_filled_32: return "time_filled_32"
        case .walk_thru_default_32: return "walk_thru_default_32"
        case .alert_filled_32: return "alert_filled_32"
        case .find_me_ios_no_permission_32: return "find_me_ios_no_permission_32"
        case .calendar_filled_32: return "calendar_filled_32"
        case .status_success_12: return "status_success_12"
        case .mccafe_filled_32: return "mccafe_filled_32"
        case .counter_default_32: return "counter_default_32"
        case .leave_at_door_default_32: return "leave_at_door_default_32"
        case .flash_default_32: return "flash_default_32"
        case .restaurant_default_32: return "restaurant_default_32"
        case .leave_at_door_filled_32: return "leave_at_door_filled_32"
        case .order_delivery_disabled_32: return "order_delivery_disabled_32"
        case .status_success_20: return "status_success_20"
        case .meet_outside_filled_32: return "meet_outside_filled_32"
        case .find_me_android_no_permission_32: return "find_me_android_no_permission_32"
        case .meet_outside_default_32: return "meet_outside_default_32"
        case .charging_filled_32: return "charging_filled_32"
        case .status_check: return "status_check"
        case .order_location_green_32: return "order_location_green_32"
        case .hide_filled_32: return "hide_filled_32"
        case .drive_thru_filled_32: return "drive_thru_filled_32"
        case .recurring_default_32: return "recurring_default_32"
        case .order_location_32: return "order_location_32"
        case .deprecated__remove_filled_32: return "deprecated__remove_filled_32"
        case .mccafe_default_32: return "mccafe_default_32"
        case .deprecated__arrow_right_filled_32: return "deprecated__arrow_right_filled_32"
        case .play_filled: return "play_filled"
        case .qr_code_filled_32: return "qr_code_filled_32"
        case .deprecated__add_filled_32: return "deprecated__add_filled_32"
        case .remove_default_32: return "remove_default_32"
        case .find_me_android_default_32: return "find_me_android_default_32"
        case .charging_default_32: return "charging_default_32"
        case .qr_code_default_32: return "qr_code_default_32"
        case .voice_filled_32: return "voice_filled_32"
        case .status_false_20v2: return "status_false_20v2"
        case .show_default_32: return "show_default_32"
        case .edit_filled_32: return "edit_filled_32"
        case .blocker_filled_32: return "blocker_filled_32"
        case .language_default_32: return "language_default_32"
        case .chevron_up_default_32: return "chevron_up_default_32"
        case .deprecated_status_alert_20_old: return "deprecated_status_alert_20_old"
        case .meal_default_32: return "meal_default_32"
        case .bag_filled_32: return "bag_filled_32"
        case .link_external_link_16: return "link_external_link_16"
        case .arrow_up_left_default_32: return "arrow_up_left_default_32"
        case .deprecated_chevron_right_filled_32: return "deprecated_chevron_right_filled_32"
        case .chevron_right_default_32: return "chevron_right_default_32"
        case .kiosk_default_32: return "kiosk_default_32"
        case .show_filled_32: return "show_filled_32"
        case .status_alert_16: return "status_alert_16"
        case .counter_filled_32: return "counter_filled_32"
        case .meet_at_door_filled_32: return "meet_at_door_filled_32"
        case .table_service_default_32: return "table_service_default_32"
        case .check_filled_32: return "check_filled_32"
        case .recents_default_32: return "recents_default_32"
        case .flash_filled_32: return "flash_filled_32"
        case .outdoor_terrace_filled_32: return "outdoor_terrace_filled_32"
        case .list_search_default_32: return "list_search_default_32"
        case .time_default_32: return "time_default_32"
        case .timer_default_32: return "timer_default_32"
        case .playground_default_32: return "playground_default_32"
        case .link_arrow: return "link_arrow"
        case .playground_filled_32: return "playground_filled_32"
        case .ios_back: return "ios_back"
        case .cold_kiosk_default_32: return "cold_kiosk_default_32"
        case .find_me_ios_default_32: return "find_me_ios_default_32"
        case .order_delivery_32: return "order_delivery_32"
        case .calendar_default_32: return "calendar_default_32"
        case .transactions_filled_32: return "transactions_filled_32"
        case .phone_alt2_default_32: return "phone_alt2_default_32"
        case .list_filled_32: return "list_filled_32"
        case .filter_active_32: return "filter_active_32"
        case .find_me_android_filled_32: return "find_me_android_filled_32"
        case .recurring_filled_32: return "recurring_filled_32"
        case .meet_at_door_default_32: return "meet_at_door_default_32"
        case .close_default_32: return "close_default_32"
        case .language_filled_32: return "language_filled_32"
        case .bar_code_default_32: return "bar_code_default_32"
        case .bar_code_filled_32: return "bar_code_filled_32"
        case .deprecated__hamburger_filled_32: return "deprecated__hamburger_filled_32"
        case .log_out_filled_32: return "log_out_filled_32"
        case .deprecated_status_alert_16_old: return "deprecated_status_alert_16_old"
        case .status_blocker_12: return "status_blocker_12"
        case .delivery_instructions_alt2_filled_32: return "delivery_instructions_alt2_filled_32"
        case .map_filled_32: return "map_filled_32"
        case .table_service_filled_32: return "table_service_filled_32"
        case .external_link_default_32: return "external_link_default_32"
        case .edit_default_32: return "edit_default_32"
        case .deprecated_chevron_left_filled_32: return "deprecated_chevron_left_filled_32"
        case .deprecated__close_filled_32: return "deprecated__close_filled_32"
        case .curbside_filled_32: return "curbside_filled_32"
        case .recents_filled_32: return "recents_filled_32"
        case .status_blocker_16: return "status_blocker_16"
        case .directions_default_32: return "directions_default_32"
        case .deprecated__nav_list_filled_32: return "deprecated__nav_list_filled_32"
        case .delivery_instructions_filled_32: return "delivery_instructions_filled_32"
        case .hamburger_default_32: return "hamburger_default_32"
        }
    }
    
    @available(iOS 13.0, macOS 10.15, *)
    public var image: Image? {
        #if canImport(SwiftUI)
        return Image(imageName, bundle: .module)
        #else
        return nil
        #endif
    }
}

// MARK: - Categories
public extension GeneratedIcons {
    static var allIcons: [GeneratedIcons] {
        return [
            .check_default_32,
            .search_default_32,
            .light_bulb_filled_32,
            .outdoor_terrace_default_32,
            .voice_default_32,
            .kiosk_filled_32,
            .accessibility_filled_32,
            .status_info_12,
            .status_blocker_20,
            .address_default_32,
            .blocker_default_32,
            .refresh_filled_32,
            .nav_list_default_32,
            .pause_default,
            .add_default_32,
            .payment_filled_32,
            .status_info_20,
            .chevron_down_default_32,
            .location_no_mobile_order_32,
            .delivery_instructions_default_32,
            .find_me_ios_filled_32,
            .meal_filled_32,
            .address_filled_32,
            .hide_default_32,
            .keypad_default_32,
            .map_default_32,
            .transactions_default_32,
            .light_off_bulb_default_32,
            .status_selected_12,
            .list_default_32,
            .status_success_16,
            .light_off_bulb_filled_32,
            .full_screen_default_32,
            .accessibility_default_32,
            .play_default,
            .minimize_full_screen_default_32,
            .payment_default_32,
            .deprecated__chevron_up_filled_32,
            .status_alert_20,
            .alert_default_32,
            .drive_thru_default_32,
            .chevron_left_default_32,
            .log_out_default_32,
            .wi_fi_default_32,
            .status_info_16,
            .status_alert_12,
            .status_selected_20,
            .refresh_default_32,
            .curbside_default_32,
            .pause_filled,
            .cold_kiosk_filled_32,
            .arrow_left_default_32,
            .restaurant_filled_32,
            .delivery_instructions_alt2_default_32,
            .eat_in_default_32,
            .light_bulb_default_32,
            .deprecated_status_alert_12_old,
            .keypad_filled_32,
            .phone_alt2_filled_32,
            .link_directions_16,
            .deprecated__external_link_filled_32,
            .bag_default_32,
            .copy_default_32,
            .status_selected_16,
            .trash_default_32,
            .eat_in_filled_32,
            .search_filled_32,
            .deprecated__chevron_down_filled_32,
            .wi_fi_filled_32,
            .arrow_right_default_32,
            .walk_thru_filled_32,
            .time_filled_32,
            .walk_thru_default_32,
            .alert_filled_32,
            .find_me_ios_no_permission_32,
            .calendar_filled_32,
            .status_success_12,
            .mccafe_filled_32,
            .counter_default_32,
            .leave_at_door_default_32,
            .flash_default_32,
            .restaurant_default_32,
            .leave_at_door_filled_32,
            .order_delivery_disabled_32,
            .status_success_20,
            .meet_outside_filled_32,
            .find_me_android_no_permission_32,
            .meet_outside_default_32,
            .charging_filled_32,
            .status_check,
            .order_location_green_32,
            .hide_filled_32,
            .drive_thru_filled_32,
            .recurring_default_32,
            .order_location_32,
            .deprecated__remove_filled_32,
            .mccafe_default_32,
            .deprecated__arrow_right_filled_32,
            .play_filled,
            .qr_code_filled_32,
            .deprecated__add_filled_32,
            .remove_default_32,
            .find_me_android_default_32,
            .charging_default_32,
            .qr_code_default_32,
            .voice_filled_32,
            .status_false_20v2,
            .show_default_32,
            .edit_filled_32,
            .blocker_filled_32,
            .language_default_32,
            .chevron_up_default_32,
            .deprecated_status_alert_20_old,
            .meal_default_32,
            .bag_filled_32,
            .link_external_link_16,
            .arrow_up_left_default_32,
            .deprecated_chevron_right_filled_32,
            .chevron_right_default_32,
            .kiosk_default_32,
            .show_filled_32,
            .status_alert_16,
            .counter_filled_32,
            .meet_at_door_filled_32,
            .table_service_default_32,
            .check_filled_32,
            .recents_default_32,
            .flash_filled_32,
            .outdoor_terrace_filled_32,
            .list_search_default_32,
            .time_default_32,
            .timer_default_32,
            .playground_default_32,
            .link_arrow,
            .playground_filled_32,
            .ios_back,
            .cold_kiosk_default_32,
            .find_me_ios_default_32,
            .order_delivery_32,
            .calendar_default_32,
            .transactions_filled_32,
            .phone_alt2_default_32,
            .list_filled_32,
            .filter_active_32,
            .find_me_android_filled_32,
            .recurring_filled_32,
            .meet_at_door_default_32,
            .close_default_32,
            .language_filled_32,
            .bar_code_default_32,
            .bar_code_filled_32,
            .deprecated__hamburger_filled_32,
            .log_out_filled_32,
            .deprecated_status_alert_16_old,
            .status_blocker_12,
            .delivery_instructions_alt2_filled_32,
            .map_filled_32,
            .table_service_filled_32,
            .external_link_default_32,
            .edit_default_32,
            .deprecated_chevron_left_filled_32,
            .deprecated__close_filled_32,
            .curbside_filled_32,
            .recents_filled_32,
            .status_blocker_16,
            .directions_default_32,
            .deprecated__nav_list_filled_32,
            .delivery_instructions_filled_32,
            .hamburger_default_32
        ]
    }
    
    static var categories: [String: [GeneratedIcons]] {
        var result: [String: [GeneratedIcons]] = [:]
        for icon in allIcons {
            let category = icon.category
            result[category, default: []].append(icon)
        }
        return result
    }
    
    var category: String {
        switch self {
                case .check_default_32: return "General"
        case .search_default_32: return "General"
        case .light_bulb_filled_32: return "General"
        case .outdoor_terrace_default_32: return "General"
        case .voice_default_32: return "General"
        case .kiosk_filled_32: return "General"
        case .accessibility_filled_32: return "General"
        case .status_info_12: return "Status"
        case .status_blocker_20: return "Status"
        case .address_default_32: return "General"
        case .blocker_default_32: return "General"
        case .refresh_filled_32: return "General"
        case .nav_list_default_32: return "Navigation"
        case .pause_default: return "General"
        case .add_default_32: return "General"
        case .payment_filled_32: return "General"
        case .status_info_20: return "Status"
        case .chevron_down_default_32: return "General"
        case .location_no_mobile_order_32: return "Map"
        case .delivery_instructions_default_32: return "General"
        case .find_me_ios_filled_32: return "General"
        case .meal_filled_32: return "General"
        case .address_filled_32: return "General"
        case .hide_default_32: return "General"
        case .keypad_default_32: return "General"
        case .map_default_32: return "Map"
        case .transactions_default_32: return "General"
        case .light_off_bulb_default_32: return "General"
        case .status_selected_12: return "Status"
        case .list_default_32: return "General"
        case .status_success_16: return "Status"
        case .light_off_bulb_filled_32: return "General"
        case .full_screen_default_32: return "General"
        case .accessibility_default_32: return "General"
        case .play_default: return "General"
        case .minimize_full_screen_default_32: return "General"
        case .payment_default_32: return "General"
        case .deprecated__chevron_up_filled_32: return "General"
        case .status_alert_20: return "Status"
        case .alert_default_32: return "Status"
        case .drive_thru_default_32: return "General"
        case .chevron_left_default_32: return "General"
        case .log_out_default_32: return "General"
        case .wi_fi_default_32: return "General"
        case .status_info_16: return "Status"
        case .status_alert_12: return "Status"
        case .status_selected_20: return "Status"
        case .refresh_default_32: return "General"
        case .curbside_default_32: return "General"
        case .pause_filled: return "General"
        case .cold_kiosk_filled_32: return "General"
        case .arrow_left_default_32: return "General"
        case .restaurant_filled_32: return "General"
        case .delivery_instructions_alt2_default_32: return "General"
        case .eat_in_default_32: return "General"
        case .light_bulb_default_32: return "General"
        case .deprecated_status_alert_12_old: return "Status"
        case .keypad_filled_32: return "General"
        case .phone_alt2_filled_32: return "General"
        case .link_directions_16: return "General"
        case .deprecated__external_link_filled_32: return "General"
        case .bag_default_32: return "General"
        case .copy_default_32: return "General"
        case .status_selected_16: return "Status"
        case .trash_default_32: return "General"
        case .eat_in_filled_32: return "General"
        case .search_filled_32: return "General"
        case .deprecated__chevron_down_filled_32: return "General"
        case .wi_fi_filled_32: return "General"
        case .arrow_right_default_32: return "General"
        case .walk_thru_filled_32: return "General"
        case .time_filled_32: return "General"
        case .walk_thru_default_32: return "General"
        case .alert_filled_32: return "Status"
        case .find_me_ios_no_permission_32: return "General"
        case .calendar_filled_32: return "General"
        case .status_success_12: return "Status"
        case .mccafe_filled_32: return "General"
        case .counter_default_32: return "General"
        case .leave_at_door_default_32: return "General"
        case .flash_default_32: return "General"
        case .restaurant_default_32: return "General"
        case .leave_at_door_filled_32: return "General"
        case .order_delivery_disabled_32: return "General"
        case .status_success_20: return "Status"
        case .meet_outside_filled_32: return "General"
        case .find_me_android_no_permission_32: return "General"
        case .meet_outside_default_32: return "General"
        case .charging_filled_32: return "General"
        case .status_check: return "Status"
        case .order_location_green_32: return "Map"
        case .hide_filled_32: return "General"
        case .drive_thru_filled_32: return "General"
        case .recurring_default_32: return "General"
        case .order_location_32: return "Map"
        case .deprecated__remove_filled_32: return "General"
        case .mccafe_default_32: return "General"
        case .deprecated__arrow_right_filled_32: return "General"
        case .play_filled: return "General"
        case .qr_code_filled_32: return "General"
        case .deprecated__add_filled_32: return "General"
        case .remove_default_32: return "General"
        case .find_me_android_default_32: return "General"
        case .charging_default_32: return "General"
        case .qr_code_default_32: return "General"
        case .voice_filled_32: return "General"
        case .status_false_20v2: return "Status"
        case .show_default_32: return "General"
        case .edit_filled_32: return "General"
        case .blocker_filled_32: return "General"
        case .language_default_32: return "General"
        case .chevron_up_default_32: return "General"
        case .deprecated_status_alert_20_old: return "Status"
        case .meal_default_32: return "General"
        case .bag_filled_32: return "General"
        case .link_external_link_16: return "General"
        case .arrow_up_left_default_32: return "General"
        case .deprecated_chevron_right_filled_32: return "General"
        case .chevron_right_default_32: return "General"
        case .kiosk_default_32: return "General"
        case .show_filled_32: return "General"
        case .status_alert_16: return "Status"
        case .counter_filled_32: return "General"
        case .meet_at_door_filled_32: return "General"
        case .table_service_default_32: return "General"
        case .check_filled_32: return "General"
        case .recents_default_32: return "General"
        case .flash_filled_32: return "General"
        case .outdoor_terrace_filled_32: return "General"
        case .list_search_default_32: return "General"
        case .time_default_32: return "General"
        case .timer_default_32: return "General"
        case .playground_default_32: return "General"
        case .link_arrow: return "General"
        case .playground_filled_32: return "General"
        case .ios_back: return "General"
        case .cold_kiosk_default_32: return "General"
        case .find_me_ios_default_32: return "General"
        case .order_delivery_32: return "General"
        case .calendar_default_32: return "General"
        case .transactions_filled_32: return "General"
        case .phone_alt2_default_32: return "General"
        case .list_filled_32: return "General"
        case .filter_active_32: return "General"
        case .find_me_android_filled_32: return "General"
        case .recurring_filled_32: return "General"
        case .meet_at_door_default_32: return "General"
        case .close_default_32: return "General"
        case .language_filled_32: return "General"
        case .bar_code_default_32: return "General"
        case .bar_code_filled_32: return "General"
        case .deprecated__hamburger_filled_32: return "General"
        case .log_out_filled_32: return "General"
        case .deprecated_status_alert_16_old: return "Status"
        case .status_blocker_12: return "Status"
        case .delivery_instructions_alt2_filled_32: return "General"
        case .map_filled_32: return "Map"
        case .table_service_filled_32: return "General"
        case .external_link_default_32: return "General"
        case .edit_default_32: return "General"
        case .deprecated_chevron_left_filled_32: return "General"
        case .deprecated__close_filled_32: return "General"
        case .curbside_filled_32: return "General"
        case .recents_filled_32: return "General"
        case .status_blocker_16: return "Status"
        case .directions_default_32: return "General"
        case .deprecated__nav_list_filled_32: return "Navigation"
        case .delivery_instructions_filled_32: return "General"
        case .hamburger_default_32: return "General"
        }
    }
    
    var variant: String {
        switch self {
                case .check_default_32: return "default"
        case .search_default_32: return "default"
        case .light_bulb_filled_32: return "filled"
        case .outdoor_terrace_default_32: return "default"
        case .voice_default_32: return "default"
        case .kiosk_filled_32: return "filled"
        case .accessibility_filled_32: return "filled"
        case .status_info_12: return "original"
        case .status_blocker_20: return "original"
        case .address_default_32: return "default"
        case .blocker_default_32: return "default"
        case .refresh_filled_32: return "filled"
        case .nav_list_default_32: return "default"
        case .pause_default: return "default"
        case .add_default_32: return "default"
        case .payment_filled_32: return "filled"
        case .status_info_20: return "original"
        case .chevron_down_default_32: return "default"
        case .location_no_mobile_order_32: return "original"
        case .delivery_instructions_default_32: return "default"
        case .find_me_ios_filled_32: return "filled"
        case .meal_filled_32: return "filled"
        case .address_filled_32: return "filled"
        case .hide_default_32: return "default"
        case .keypad_default_32: return "default"
        case .map_default_32: return "default"
        case .transactions_default_32: return "default"
        case .light_off_bulb_default_32: return "default"
        case .status_selected_12: return "original"
        case .list_default_32: return "default"
        case .status_success_16: return "original"
        case .light_off_bulb_filled_32: return "filled"
        case .full_screen_default_32: return "default"
        case .accessibility_default_32: return "default"
        case .play_default: return "default"
        case .minimize_full_screen_default_32: return "default"
        case .payment_default_32: return "default"
        case .deprecated__chevron_up_filled_32: return "filled"
        case .status_alert_20: return "original"
        case .alert_default_32: return "default"
        case .drive_thru_default_32: return "default"
        case .chevron_left_default_32: return "default"
        case .log_out_default_32: return "default"
        case .wi_fi_default_32: return "default"
        case .status_info_16: return "original"
        case .status_alert_12: return "original"
        case .status_selected_20: return "original"
        case .refresh_default_32: return "default"
        case .curbside_default_32: return "default"
        case .pause_filled: return "filled"
        case .cold_kiosk_filled_32: return "filled"
        case .arrow_left_default_32: return "default"
        case .restaurant_filled_32: return "filled"
        case .delivery_instructions_alt2_default_32: return "default"
        case .eat_in_default_32: return "default"
        case .light_bulb_default_32: return "default"
        case .deprecated_status_alert_12_old: return "original"
        case .keypad_filled_32: return "filled"
        case .phone_alt2_filled_32: return "filled"
        case .link_directions_16: return "original"
        case .deprecated__external_link_filled_32: return "filled"
        case .bag_default_32: return "default"
        case .copy_default_32: return "default"
        case .status_selected_16: return "original"
        case .trash_default_32: return "default"
        case .eat_in_filled_32: return "filled"
        case .search_filled_32: return "filled"
        case .deprecated__chevron_down_filled_32: return "filled"
        case .wi_fi_filled_32: return "filled"
        case .arrow_right_default_32: return "default"
        case .walk_thru_filled_32: return "filled"
        case .time_filled_32: return "filled"
        case .walk_thru_default_32: return "default"
        case .alert_filled_32: return "filled"
        case .find_me_ios_no_permission_32: return "original"
        case .calendar_filled_32: return "filled"
        case .status_success_12: return "original"
        case .mccafe_filled_32: return "filled"
        case .counter_default_32: return "default"
        case .leave_at_door_default_32: return "default"
        case .flash_default_32: return "default"
        case .restaurant_default_32: return "default"
        case .leave_at_door_filled_32: return "filled"
        case .order_delivery_disabled_32: return "original"
        case .status_success_20: return "original"
        case .meet_outside_filled_32: return "filled"
        case .find_me_android_no_permission_32: return "original"
        case .meet_outside_default_32: return "default"
        case .charging_filled_32: return "filled"
        case .status_check: return "original"
        case .order_location_green_32: return "original"
        case .hide_filled_32: return "filled"
        case .drive_thru_filled_32: return "filled"
        case .recurring_default_32: return "default"
        case .order_location_32: return "original"
        case .deprecated__remove_filled_32: return "filled"
        case .mccafe_default_32: return "default"
        case .deprecated__arrow_right_filled_32: return "filled"
        case .play_filled: return "filled"
        case .qr_code_filled_32: return "filled"
        case .deprecated__add_filled_32: return "filled"
        case .remove_default_32: return "default"
        case .find_me_android_default_32: return "default"
        case .charging_default_32: return "default"
        case .qr_code_default_32: return "default"
        case .voice_filled_32: return "filled"
        case .status_false_20v2: return "original"
        case .show_default_32: return "default"
        case .edit_filled_32: return "filled"
        case .blocker_filled_32: return "filled"
        case .language_default_32: return "default"
        case .chevron_up_default_32: return "default"
        case .deprecated_status_alert_20_old: return "original"
        case .meal_default_32: return "default"
        case .bag_filled_32: return "filled"
        case .link_external_link_16: return "original"
        case .arrow_up_left_default_32: return "default"
        case .deprecated_chevron_right_filled_32: return "filled"
        case .chevron_right_default_32: return "default"
        case .kiosk_default_32: return "default"
        case .show_filled_32: return "filled"
        case .status_alert_16: return "original"
        case .counter_filled_32: return "filled"
        case .meet_at_door_filled_32: return "filled"
        case .table_service_default_32: return "default"
        case .check_filled_32: return "filled"
        case .recents_default_32: return "default"
        case .flash_filled_32: return "filled"
        case .outdoor_terrace_filled_32: return "filled"
        case .list_search_default_32: return "default"
        case .time_default_32: return "default"
        case .timer_default_32: return "default"
        case .playground_default_32: return "default"
        case .link_arrow: return "original"
        case .playground_filled_32: return "filled"
        case .ios_back: return "original"
        case .cold_kiosk_default_32: return "default"
        case .find_me_ios_default_32: return "default"
        case .order_delivery_32: return "original"
        case .calendar_default_32: return "default"
        case .transactions_filled_32: return "filled"
        case .phone_alt2_default_32: return "default"
        case .list_filled_32: return "filled"
        case .filter_active_32: return "original"
        case .find_me_android_filled_32: return "filled"
        case .recurring_filled_32: return "filled"
        case .meet_at_door_default_32: return "default"
        case .close_default_32: return "default"
        case .language_filled_32: return "filled"
        case .bar_code_default_32: return "default"
        case .bar_code_filled_32: return "filled"
        case .deprecated__hamburger_filled_32: return "filled"
        case .log_out_filled_32: return "filled"
        case .deprecated_status_alert_16_old: return "original"
        case .status_blocker_12: return "original"
        case .delivery_instructions_alt2_filled_32: return "filled"
        case .map_filled_32: return "filled"
        case .table_service_filled_32: return "filled"
        case .external_link_default_32: return "default"
        case .edit_default_32: return "default"
        case .deprecated_chevron_left_filled_32: return "filled"
        case .deprecated__close_filled_32: return "filled"
        case .curbside_filled_32: return "filled"
        case .recents_filled_32: return "filled"
        case .status_blocker_16: return "original"
        case .directions_default_32: return "default"
        case .deprecated__nav_list_filled_32: return "filled"
        case .delivery_instructions_filled_32: return "filled"
        case .hamburger_default_32: return "default"
        }
    }
}