// swiftlint:disable all
// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

#if os(macOS)
  import AppKit
#elseif os(iOS)
  import UIKit
#elseif os(tvOS) || os(watchOS)
  import UIKit
#endif
#if canImport(SwiftUI)
  import SwiftUI
#endif

// Deprecated typealiases
@available(*, deprecated, renamed: "ImageAsset.Image", message: "This typealias will be removed in SwiftGen 7.0")
public typealias AssetImageTypeAlias = ImageAsset.Image

// swiftlint:disable superfluous_disable_command file_length implicit_return

// MARK: - Asset Catalogs

// swiftlint:disable identifier_name line_length nesting type_body_length type_name
public enum GeneratedAssets {
  public enum FeelGoodIcons {
    public static let icEditDefault32 = ImageAsset(name: "ic_edit_default_32")
    public static let icEditFilled32 = ImageAsset(name: "ic_edit_filled_32")
    public static let icLightBulbDefault32 = ImageAsset(name: "ic_light_bulb_default_32")
    public static let icLightBulbFilled32 = ImageAsset(name: "ic_light_bulb_filled_32")
    public static let icLightOffBulbDefault32 = ImageAsset(name: "ic_light_off_bulb_default_32")
    public static let icLightOffBulbFilled32 = ImageAsset(name: "ic_light_off_bulb_filled_32")
    public static let icListSearchDefault32 = ImageAsset(name: "ic_list_search_default_32")
    public static let icPauseDefault = ImageAsset(name: "ic_pause_default")
    public static let icPauseFilled = ImageAsset(name: "ic_pause_filled")
    public static let icPlayDefault = ImageAsset(name: "ic_play_default")
    public static let icPlayFilled = ImageAsset(name: "ic_play_filled")
    public static let icPlaygroundDefault32 = ImageAsset(name: "ic_playground_default_32")
    public static let icPlaygroundFilled32 = ImageAsset(name: "ic_playground_filled_32")
    public static let icRefreshDefault32 = ImageAsset(name: "ic_refresh_default_32")
    public static let icRefreshFilled32 = ImageAsset(name: "ic_refresh_filled_32")
    public static let icSearchDefault32 = ImageAsset(name: "ic_search_default_32")
    public static let icSearchFilled32 = ImageAsset(name: "ic_search_filled_32")
  }
  public enum GeneralIcons {
    public static let deprecatedIcAddFilled32 = ImageAsset(name: "deprecated__ic_add_filled_32")
    public static let deprecatedIcArrowRightFilled32 = ImageAsset(name: "deprecated__ic_arrow_right_filled_32")
    public static let deprecatedIcChevronDownFilled32 = ImageAsset(name: "deprecated__ic_chevron_down_filled_32")
    public static let deprecatedIcChevronUpFilled32 = ImageAsset(name: "deprecated__ic_chevron_up_filled_32")
    public static let deprecatedIcCloseFilled32 = ImageAsset(name: "deprecated__ic_close_filled_32")
    public static let deprecatedIcExternalLinkFilled32 = ImageAsset(name: "deprecated__ic_external_link_filled_32")
    public static let deprecatedIcHamburgerFilled32 = ImageAsset(name: "deprecated__ic_hamburger_filled_32")
    public static let deprecatedIcNavListFilled32 = ImageAsset(name: "deprecated__ic_nav_list_filled_32")
    public static let deprecatedIcRemoveFilled32 = ImageAsset(name: "deprecated__ic_remove_filled_32")
    public static let deprecatedIcChevronLeftFilled32 = ImageAsset(name: "deprecated_ic_chevron_left_filled_32")
    public static let deprecatedIcChevronRightFilled32 = ImageAsset(name: "deprecated_ic_chevron_right_filled_32")
    public static let flagac = ImageAsset(name: "flagac")
    public static let flagad = ImageAsset(name: "flagad")
    public static let flagae = ImageAsset(name: "flagae")
    public static let flagaf = ImageAsset(name: "flagaf")
    public static let flagag = ImageAsset(name: "flagag")
    public static let flagai = ImageAsset(name: "flagai")
    public static let flagal = ImageAsset(name: "flagal")
    public static let flagam = ImageAsset(name: "flagam")
    public static let flagao = ImageAsset(name: "flagao")
    public static let flagaq = ImageAsset(name: "flagaq")
    public static let flagar = ImageAsset(name: "flagar")
    public static let flagas = ImageAsset(name: "flagas")
    public static let flagat = ImageAsset(name: "flagat")
    public static let flagau = ImageAsset(name: "flagau")
    public static let flagaw = ImageAsset(name: "flagaw")
    public static let flagax = ImageAsset(name: "flagax")
    public static let flagaz = ImageAsset(name: "flagaz")
    public static let flagba = ImageAsset(name: "flagba")
    public static let flagbb = ImageAsset(name: "flagbb")
    public static let flagbd = ImageAsset(name: "flagbd")
    public static let flagbe = ImageAsset(name: "flagbe")
    public static let flagbf = ImageAsset(name: "flagbf")
    public static let flagbg = ImageAsset(name: "flagbg")
    public static let flagbh = ImageAsset(name: "flagbh")
    public static let flagbi = ImageAsset(name: "flagbi")
    public static let flagbj = ImageAsset(name: "flagbj")
    public static let flagbl = ImageAsset(name: "flagbl")
    public static let flagbm = ImageAsset(name: "flagbm")
    public static let flagbn = ImageAsset(name: "flagbn")
    public static let flagbo = ImageAsset(name: "flagbo")
    public static let flagbq = ImageAsset(name: "flagbq")
    public static let flagbr = ImageAsset(name: "flagbr")
    public static let flagbs = ImageAsset(name: "flagbs")
    public static let flagbt = ImageAsset(name: "flagbt")
    public static let flagbv = ImageAsset(name: "flagbv")
    public static let flagbw = ImageAsset(name: "flagbw")
    public static let flagby = ImageAsset(name: "flagby")
    public static let flagbz = ImageAsset(name: "flagbz")
    public static let flagca = ImageAsset(name: "flagca")
    public static let flagcc = ImageAsset(name: "flagcc")
    public static let flagcd = ImageAsset(name: "flagcd")
    public static let flagcf = ImageAsset(name: "flagcf")
    public static let flagcg = ImageAsset(name: "flagcg")
    public static let flagch = ImageAsset(name: "flagch")
    public static let flagci = ImageAsset(name: "flagci")
    public static let flagck = ImageAsset(name: "flagck")
    public static let flagcl = ImageAsset(name: "flagcl")
    public static let flagcm = ImageAsset(name: "flagcm")
    public static let flagcn = ImageAsset(name: "flagcn")
    public static let flagco = ImageAsset(name: "flagco")
    public static let flagcr = ImageAsset(name: "flagcr")
    public static let flagcu = ImageAsset(name: "flagcu")
    public static let flagcv = ImageAsset(name: "flagcv")
    public static let flagcw = ImageAsset(name: "flagcw")
    public static let flagcx = ImageAsset(name: "flagcx")
    public static let flagcy = ImageAsset(name: "flagcy")
    public static let flagcz = ImageAsset(name: "flagcz")
    public static let flagde = ImageAsset(name: "flagde")
    public static let flagdj = ImageAsset(name: "flagdj")
    public static let flagdk = ImageAsset(name: "flagdk")
    public static let flagdm = ImageAsset(name: "flagdm")
    public static let flagdo = ImageAsset(name: "flagdo")
    public static let flagdz = ImageAsset(name: "flagdz")
    public static let flagec = ImageAsset(name: "flagec")
    public static let flagee = ImageAsset(name: "flagee")
    public static let flageg = ImageAsset(name: "flageg")
    public static let flageh = ImageAsset(name: "flageh")
    public static let flager = ImageAsset(name: "flager")
    public static let flages = ImageAsset(name: "flages")
    public static let flaget = ImageAsset(name: "flaget")
    public static let flageu = ImageAsset(name: "flageu")
    public static let flagfi = ImageAsset(name: "flagfi")
    public static let flagfj = ImageAsset(name: "flagfj")
    public static let flagfk = ImageAsset(name: "flagfk")
    public static let flagfm = ImageAsset(name: "flagfm")
    public static let flagfo = ImageAsset(name: "flagfo")
    public static let flagfr = ImageAsset(name: "flagfr")
    public static let flagga = ImageAsset(name: "flagga")
    public static let flaggb = ImageAsset(name: "flaggb")
    public static let flaggd = ImageAsset(name: "flaggd")
    public static let flagge = ImageAsset(name: "flagge")
    public static let flaggeAb = ImageAsset(name: "flagge_ab")
    public static let flaggeOs = ImageAsset(name: "flagge_os")
    public static let flaggf = ImageAsset(name: "flaggf")
    public static let flaggg = ImageAsset(name: "flaggg")
    public static let flaggh = ImageAsset(name: "flaggh")
    public static let flaggi = ImageAsset(name: "flaggi")
    public static let flaggl = ImageAsset(name: "flaggl")
    public static let flaggm = ImageAsset(name: "flaggm")
    public static let flaggn = ImageAsset(name: "flaggn")
    public static let flaggp = ImageAsset(name: "flaggp")
    public static let flaggq = ImageAsset(name: "flaggq")
    public static let flaggr = ImageAsset(name: "flaggr")
    public static let flaggs = ImageAsset(name: "flaggs")
    public static let flaggt = ImageAsset(name: "flaggt")
    public static let flaggu = ImageAsset(name: "flaggu")
    public static let flaggw = ImageAsset(name: "flaggw")
    public static let flaggy = ImageAsset(name: "flaggy")
    public static let flaghk = ImageAsset(name: "flaghk")
    public static let flaghm = ImageAsset(name: "flaghm")
    public static let flaghn = ImageAsset(name: "flaghn")
    public static let flaghr = ImageAsset(name: "flaghr")
    public static let flaght = ImageAsset(name: "flaght")
    public static let flaghu = ImageAsset(name: "flaghu")
    public static let flagid = ImageAsset(name: "flagid")
    public static let flagie = ImageAsset(name: "flagie")
    public static let flagil = ImageAsset(name: "flagil")
    public static let flagim = ImageAsset(name: "flagim")
    public static let flagin = ImageAsset(name: "flagin")
    public static let flagio = ImageAsset(name: "flagio")
    public static let flagiq = ImageAsset(name: "flagiq")
    public static let flagir = ImageAsset(name: "flagir")
    public static let flagis = ImageAsset(name: "flagis")
    public static let flagit = ImageAsset(name: "flagit")
    public static let flagje = ImageAsset(name: "flagje")
    public static let flagjm = ImageAsset(name: "flagjm")
    public static let flagjo = ImageAsset(name: "flagjo")
    public static let flagjp = ImageAsset(name: "flagjp")
    public static let flagke = ImageAsset(name: "flagke")
    public static let flagkg = ImageAsset(name: "flagkg")
    public static let flagkh = ImageAsset(name: "flagkh")
    public static let flagki = ImageAsset(name: "flagki")
    public static let flagkm = ImageAsset(name: "flagkm")
    public static let flagkn = ImageAsset(name: "flagkn")
    public static let flagkp = ImageAsset(name: "flagkp")
    public static let flagkr = ImageAsset(name: "flagkr")
    public static let flagkw = ImageAsset(name: "flagkw")
    public static let flagky = ImageAsset(name: "flagky")
    public static let flagkz = ImageAsset(name: "flagkz")
    public static let flagla = ImageAsset(name: "flagla")
    public static let flaglb = ImageAsset(name: "flaglb")
    public static let flaglc = ImageAsset(name: "flaglc")
    public static let flagli = ImageAsset(name: "flagli")
    public static let flaglk = ImageAsset(name: "flaglk")
    public static let flaglr = ImageAsset(name: "flaglr")
    public static let flagls = ImageAsset(name: "flagls")
    public static let flaglt = ImageAsset(name: "flaglt")
    public static let flaglu = ImageAsset(name: "flaglu")
    public static let flaglv = ImageAsset(name: "flaglv")
    public static let flagly = ImageAsset(name: "flagly")
    public static let flagma = ImageAsset(name: "flagma")
    public static let flagmc = ImageAsset(name: "flagmc")
    public static let flagmd = ImageAsset(name: "flagmd")
    public static let flagme = ImageAsset(name: "flagme")
    public static let flagmf = ImageAsset(name: "flagmf")
    public static let flagmg = ImageAsset(name: "flagmg")
    public static let flagmh = ImageAsset(name: "flagmh")
    public static let flagmk = ImageAsset(name: "flagmk")
    public static let flagml = ImageAsset(name: "flagml")
    public static let flagmm = ImageAsset(name: "flagmm")
    public static let flagmn = ImageAsset(name: "flagmn")
    public static let flagmo = ImageAsset(name: "flagmo")
    public static let flagmp = ImageAsset(name: "flagmp")
    public static let flagmq = ImageAsset(name: "flagmq")
    public static let flagmr = ImageAsset(name: "flagmr")
    public static let flagms = ImageAsset(name: "flagms")
    public static let flagmt = ImageAsset(name: "flagmt")
    public static let flagmu = ImageAsset(name: "flagmu")
    public static let flagmv = ImageAsset(name: "flagmv")
    public static let flagmw = ImageAsset(name: "flagmw")
    public static let flagmx = ImageAsset(name: "flagmx")
    public static let flagmy = ImageAsset(name: "flagmy")
    public static let flagmz = ImageAsset(name: "flagmz")
    public static let flagna = ImageAsset(name: "flagna")
    public static let flagnc = ImageAsset(name: "flagnc")
    public static let flagne = ImageAsset(name: "flagne")
    public static let flagnf = ImageAsset(name: "flagnf")
    public static let flagng = ImageAsset(name: "flagng")
    public static let flagni = ImageAsset(name: "flagni")
    public static let flagnl = ImageAsset(name: "flagnl")
    public static let flagno = ImageAsset(name: "flagno")
    public static let flagnp = ImageAsset(name: "flagnp")
    public static let flagnr = ImageAsset(name: "flagnr")
    public static let flagnu = ImageAsset(name: "flagnu")
    public static let flagnz = ImageAsset(name: "flagnz")
    public static let flagom = ImageAsset(name: "flagom")
    public static let flagpa = ImageAsset(name: "flagpa")
    public static let flagpe = ImageAsset(name: "flagpe")
    public static let flagpf = ImageAsset(name: "flagpf")
    public static let flagpg = ImageAsset(name: "flagpg")
    public static let flagph = ImageAsset(name: "flagph")
    public static let flagpk = ImageAsset(name: "flagpk")
    public static let flagpl = ImageAsset(name: "flagpl")
    public static let flagplaceholder = ImageAsset(name: "flagplaceholder")
    public static let flagpm = ImageAsset(name: "flagpm")
    public static let flagpn = ImageAsset(name: "flagpn")
    public static let flagpr = ImageAsset(name: "flagpr")
    public static let flagps = ImageAsset(name: "flagps")
    public static let flagpt = ImageAsset(name: "flagpt")
    public static let flagpw = ImageAsset(name: "flagpw")
    public static let flagpy = ImageAsset(name: "flagpy")
    public static let flagqa = ImageAsset(name: "flagqa")
    public static let flagre = ImageAsset(name: "flagre")
    public static let flagro = ImageAsset(name: "flagro")
    public static let flagrs = ImageAsset(name: "flagrs")
    public static let flagru = ImageAsset(name: "flagru")
    public static let flagrw = ImageAsset(name: "flagrw")
    public static let flagsa = ImageAsset(name: "flagsa")
    public static let flagsb = ImageAsset(name: "flagsb")
    public static let flagsc = ImageAsset(name: "flagsc")
    public static let flagsd = ImageAsset(name: "flagsd")
    public static let flagse = ImageAsset(name: "flagse")
    public static let flagsg = ImageAsset(name: "flagsg")
    public static let flagsh = ImageAsset(name: "flagsh")
    public static let flagsi = ImageAsset(name: "flagsi")
    public static let flagsj = ImageAsset(name: "flagsj")
    public static let flagsk = ImageAsset(name: "flagsk")
    public static let flagsl = ImageAsset(name: "flagsl")
    public static let flagsm = ImageAsset(name: "flagsm")
    public static let flagsn = ImageAsset(name: "flagsn")
    public static let flagso = ImageAsset(name: "flagso")
    public static let flagsr = ImageAsset(name: "flagsr")
    public static let flagss = ImageAsset(name: "flagss")
    public static let flagst = ImageAsset(name: "flagst")
    public static let flagsv = ImageAsset(name: "flagsv")
    public static let flagsx = ImageAsset(name: "flagsx")
    public static let flagsy = ImageAsset(name: "flagsy")
    public static let flagsz = ImageAsset(name: "flagsz")
    public static let flagta = ImageAsset(name: "flagta")
    public static let flagtc = ImageAsset(name: "flagtc")
    public static let flagtd = ImageAsset(name: "flagtd")
    public static let flagtf = ImageAsset(name: "flagtf")
    public static let flagtg = ImageAsset(name: "flagtg")
    public static let flagth = ImageAsset(name: "flagth")
    public static let flagtj = ImageAsset(name: "flagtj")
    public static let flagtk = ImageAsset(name: "flagtk")
    public static let flagtl = ImageAsset(name: "flagtl")
    public static let flagtm = ImageAsset(name: "flagtm")
    public static let flagtn = ImageAsset(name: "flagtn")
    public static let flagto = ImageAsset(name: "flagto")
    public static let flagtr = ImageAsset(name: "flagtr")
    public static let flagtt = ImageAsset(name: "flagtt")
    public static let flagtv = ImageAsset(name: "flagtv")
    public static let flagtw = ImageAsset(name: "flagtw")
    public static let flagtz = ImageAsset(name: "flagtz")
    public static let flagua = ImageAsset(name: "flagua")
    public static let flagug = ImageAsset(name: "flagug")
    public static let flagum = ImageAsset(name: "flagum")
    public static let flagus = ImageAsset(name: "flagus")
    public static let flaguy = ImageAsset(name: "flaguy")
    public static let flaguz = ImageAsset(name: "flaguz")
    public static let flagva = ImageAsset(name: "flagva")
    public static let flagvc = ImageAsset(name: "flagvc")
    public static let flagve = ImageAsset(name: "flagve")
    public static let flagvg = ImageAsset(name: "flagvg")
    public static let flagvi = ImageAsset(name: "flagvi")
    public static let flagvn = ImageAsset(name: "flagvn")
    public static let flagvu = ImageAsset(name: "flagvu")
    public static let flagwf = ImageAsset(name: "flagwf")
    public static let flagws = ImageAsset(name: "flagws")
    public static let flagxk = ImageAsset(name: "flagxk")
    public static let flagye = ImageAsset(name: "flagye")
    public static let flagyt = ImageAsset(name: "flagyt")
    public static let flagza = ImageAsset(name: "flagza")
    public static let flagzm = ImageAsset(name: "flagzm")
    public static let flagzw = ImageAsset(name: "flagzw")
    public static let icAccessibilityDefault32 = ImageAsset(name: "ic_accessibility_default_32")
    public static let icAccessibilityFilled32 = ImageAsset(name: "ic_accessibility_filled_32")
    public static let icAddDefault32 = ImageAsset(name: "ic_add_default_32")
    public static let icAddressDefault32 = ImageAsset(name: "ic_address_default_32")
    public static let icAddressFilled32 = ImageAsset(name: "ic_address_filled_32")
    public static let icArrowLeftDefault32 = ImageAsset(name: "ic_arrow_left_default_32")
    public static let icArrowRightDefault32 = ImageAsset(name: "ic_arrow_right_default_32")
    public static let icArrowUpLeftDefault32 = ImageAsset(name: "ic_arrow_up_left_default_32")
    public static let icBagDefault32 = ImageAsset(name: "ic_bag_default_32")
    public static let icBagFilled32 = ImageAsset(name: "ic_bag_filled_32")
    public static let icBarCodeDefault32 = ImageAsset(name: "ic_bar_code_default_32")
    public static let icBarCodeFilled32 = ImageAsset(name: "ic_bar_code_filled_32")
    public static let icCalendarDefault32 = ImageAsset(name: "ic_calendar_default_32")
    public static let icCalendarFilled32 = ImageAsset(name: "ic_calendar_filled_32")
    public static let icChargingDefault32 = ImageAsset(name: "ic_charging_default_32")
    public static let icChargingFilled32 = ImageAsset(name: "ic_charging_filled_32")
    public static let icCheckDefault32 = ImageAsset(name: "ic_check_default_32")
    public static let icCheckFilled32 = ImageAsset(name: "ic_check_filled_32")
    public static let icChevronDownDefault32 = ImageAsset(name: "ic_chevron_down_default_32")
    public static let icChevronLeftDefault32 = ImageAsset(name: "ic_chevron_left_default_32")
    public static let icChevronRightDefault32 = ImageAsset(name: "ic_chevron_right_default_32")
    public static let icChevronUpDefault32 = ImageAsset(name: "ic_chevron_up_default_32")
    public static let icCloseDefault32 = ImageAsset(name: "ic_close_default_32")
    public static let icColdKioskDefault32 = ImageAsset(name: "ic_cold_kiosk_default_32")
    public static let icColdKioskFilled32 = ImageAsset(name: "ic_cold_kiosk_filled_32")
    public static let icCopyDefault32 = ImageAsset(name: "ic_copy_default_32")
    public static let icCounterDefault32 = ImageAsset(name: "ic_counter_default_32")
    public static let icCounterFilled32 = ImageAsset(name: "ic_counter_filled_32")
    public static let icCurbsideDefault32 = ImageAsset(name: "ic_curbside_default_32")
    public static let icCurbsideFilled32 = ImageAsset(name: "ic_curbside_filled_32")
    public static let icDirectionsDefault32 = ImageAsset(name: "ic_directions_default_32")
    public static let icDriveThruDefault32 = ImageAsset(name: "ic_drive_thru_default_32")
    public static let icDriveThruFilled32 = ImageAsset(name: "ic_drive_thru_filled_32")
    public static let icEatInDefault32 = ImageAsset(name: "ic_eat_in_default_32")
    public static let icEatInFilled32 = ImageAsset(name: "ic_eat_in_filled_32")
    public static let icExternalLinkDefault32 = ImageAsset(name: "ic_external_link_default_32")
    public static let icFilterActive32 = ImageAsset(name: "ic_filter_active_32")
    public static let icFindMeAndroidDefault32 = ImageAsset(name: "ic_find_me_android_default_32")
    public static let icFindMeAndroidFilled32 = ImageAsset(name: "ic_find_me_android_filled_32")
    public static let icFindMeAndroidNoPermission32 = ImageAsset(name: "ic_find_me_android_no_permission_32")
    public static let icFindMeIosDefault32 = ImageAsset(name: "ic_find_me_ios_default_32")
    public static let icFindMeIosFilled32 = ImageAsset(name: "ic_find_me_ios_filled_32")
    public static let icFindMeIosNoPermission32 = ImageAsset(name: "ic_find_me_ios_no_permission_32")
    public static let icFlashDefault32 = ImageAsset(name: "ic_flash_default_32")
    public static let icFlashFilled32 = ImageAsset(name: "ic_flash_filled_32")
    public static let icFullScreenDefault32 = ImageAsset(name: "ic_full_screen_default_32")
    public static let icHamburgerDefault32 = ImageAsset(name: "ic_hamburger_default_32")
    public static let icHideDefault32 = ImageAsset(name: "ic_hide_default_32")
    public static let icHideFilled32 = ImageAsset(name: "ic_hide_filled_32")
    public static let icIosBack = ImageAsset(name: "ic_ios_back")
    public static let icKeypadDefault32 = ImageAsset(name: "ic_keypad_default_32")
    public static let icKeypadFilled32 = ImageAsset(name: "ic_keypad_filled_32")
    public static let icKioskDefault32 = ImageAsset(name: "ic_kiosk_default_32")
    public static let icKioskFilled32 = ImageAsset(name: "ic_kiosk_filled_32")
    public static let icLanguageDefault32 = ImageAsset(name: "ic_language_default_32")
    public static let icLanguageFilled32 = ImageAsset(name: "ic_language_filled_32")
    public static let icLeaveAtDoorDefault32 = ImageAsset(name: "ic_leave_at_door_default_32")
    public static let icLeaveAtDoorFilled32 = ImageAsset(name: "ic_leave_at_door_filled_32")
    public static let icLinkArrow = ImageAsset(name: "ic_link_arrow")
    public static let icLinkDirections16 = ImageAsset(name: "ic_link_directions_16")
    public static let icLinkExternalLink16 = ImageAsset(name: "ic_link_external_link_16")
    public static let icListDefault32 = ImageAsset(name: "ic_list_default_32")
    public static let icListFilled32 = ImageAsset(name: "ic_list_filled_32")
    public static let icLogOutDefault32 = ImageAsset(name: "ic_log_out_default_32")
    public static let icLogOutFilled32 = ImageAsset(name: "ic_log_out_filled_32")
    public static let icMccafeDefault32 = ImageAsset(name: "ic_mccafe_default_32")
    public static let icMccafeFilled32 = ImageAsset(name: "ic_mccafe_filled_32")
    public static let icMealDefault32 = ImageAsset(name: "ic_meal_default_32")
    public static let icMealFilled32 = ImageAsset(name: "ic_meal_filled_32")
    public static let icMeetAtDoorDefault32 = ImageAsset(name: "ic_meet_at_door_default_32")
    public static let icMeetAtDoorFilled32 = ImageAsset(name: "ic_meet_at_door_filled_32")
    public static let icMeetOutsideDefault32 = ImageAsset(name: "ic_meet_outside_default_32")
    public static let icMeetOutsideFilled32 = ImageAsset(name: "ic_meet_outside_filled_32")
    public static let icMinimizeFullScreenDefault32 = ImageAsset(name: "ic_minimize_full_screen_default_32")
    public static let icNavListDefault32 = ImageAsset(name: "ic_nav_list_default_32")
    public static let icOutdoorTerraceDefault32 = ImageAsset(name: "ic_outdoor_terrace_default_32")
    public static let icOutdoorTerraceFilled32 = ImageAsset(name: "ic_outdoor_terrace_filled_32")
    public static let icPaymentDefault32 = ImageAsset(name: "ic_payment_default_32")
    public static let icPaymentFilled32 = ImageAsset(name: "ic_payment_filled_32")
    public static let icPhoneAlt2Default32 = ImageAsset(name: "ic_phone_alt2_default_32")
    public static let icPhoneAlt2Filled32 = ImageAsset(name: "ic_phone_alt2_filled_32")
    public static let icQrCodeDefault32 = ImageAsset(name: "ic_qr_code_default_32")
    public static let icQrCodeFilled32 = ImageAsset(name: "ic_qr_code_filled_32")
    public static let icRecentsDefault32 = ImageAsset(name: "ic_recents_default_32")
    public static let icRecentsFilled32 = ImageAsset(name: "ic_recents_filled_32")
    public static let icRecurringDefault32 = ImageAsset(name: "ic_recurring_default_32")
    public static let icRecurringFilled32 = ImageAsset(name: "ic_recurring_filled_32")
    public static let icRemoveDefault32 = ImageAsset(name: "ic_remove_default_32")
    public static let icRestaurantDefault32 = ImageAsset(name: "ic_restaurant_default_32")
    public static let icRestaurantFilled32 = ImageAsset(name: "ic_restaurant_filled_32")
    public static let icShowDefault32 = ImageAsset(name: "ic_show_default_32")
    public static let icShowFilled32 = ImageAsset(name: "ic_show_filled_32")
    public static let icTableServiceDefault32 = ImageAsset(name: "ic_table_service_default_32")
    public static let icTableServiceFilled32 = ImageAsset(name: "ic_table_service_filled_32")
    public static let icTimeDefault32 = ImageAsset(name: "ic_time_default_32")
    public static let icTimeFilled32 = ImageAsset(name: "ic_time_filled_32")
    public static let icTimerDefault32 = ImageAsset(name: "ic_timer_default_32")
    public static let icTransactionsDefault32 = ImageAsset(name: "ic_transactions_default_32")
    public static let icTransactionsFilled32 = ImageAsset(name: "ic_transactions_filled_32")
    public static let icTrashDefault32 = ImageAsset(name: "ic_trash_default_32")
    public static let icVoiceDefault32 = ImageAsset(name: "ic_voice_default_32")
    public static let icVoiceFilled32 = ImageAsset(name: "ic_voice_filled_32")
    public static let icWalkThruDefault32 = ImageAsset(name: "ic_walk_thru_default_32")
    public static let icWalkThruFilled32 = ImageAsset(name: "ic_walk_thru_filled_32")
    public static let icWiFiDefault32 = ImageAsset(name: "ic_wi_fi_default_32")
    public static let icWiFiFilled32 = ImageAsset(name: "ic_wi_fi_filled_32")
    public static let stateactiveColorred = ImageAsset(name: "stateactive_colorred")
    public static let statedefaultColorred = ImageAsset(name: "statedefault_colorred")
    public static let statedefaultColoryellow = ImageAsset(name: "statedefault_coloryellow")
    public static let statedisabledColorgrey = ImageAsset(name: "statedisabled_colorgrey")
    public static let statestate5Coloryellow = ImageAsset(name: "statestate5_coloryellow")
  }
  public enum Icons {
    public static let icLightBulbDefault32 = ImageAsset(name: "ic_light_bulb_default_32")
    public static let icStatusSuccess16 = ImageAsset(name: "ic_status_success_16")
    public static let mapPinSingleDefault = ImageAsset(name: "map_pin_single_default")
  }
  public enum MapIcons {
    public static let icDeliveryInstructionsAlt2Default32 = ImageAsset(name: "ic_delivery_instructions_alt2_default_32")
    public static let icDeliveryInstructionsAlt2Filled32 = ImageAsset(name: "ic_delivery_instructions_alt2_filled_32")
    public static let icDeliveryInstructionsDefault32 = ImageAsset(name: "ic_delivery_instructions_default_32")
    public static let icDeliveryInstructionsFilled32 = ImageAsset(name: "ic_delivery_instructions_filled_32")
    public static let icLocationNoMobileOrder32 = ImageAsset(name: "ic_location_no_mobile_order_32")
    public static let icMapDefault32 = ImageAsset(name: "ic_map_default_32")
    public static let icMapFilled32 = ImageAsset(name: "ic_map_filled_32")
    public static let icOrderDelivery32 = ImageAsset(name: "ic_order_delivery_32")
    public static let icOrderDeliveryDisabled32 = ImageAsset(name: "ic_order_delivery_disabled_32")
    public static let icOrderLocation32 = ImageAsset(name: "ic_order_location_32")
    public static let icOrderLocationGreen32 = ImageAsset(name: "ic_order_location_green_32")
    public static let mapPinSingleDefault = ImageAsset(name: "map_pin_single_default")
    public static let mapPinSingleDefaultGreen = ImageAsset(name: "map_pin_single_default_green")
    public static let mapPinSingleDisabled = ImageAsset(name: "map_pin_single_disabled")
    public static let mapPinSingleDisabledGreen = ImageAsset(name: "map_pin_single_disabled_green")
    public static let mapPinSingleNoMobileOrderDefault = ImageAsset(name: "map_pin_single_no_mobile_order_default")
    public static let mapPinSingleNoMobileOrderDisabled = ImageAsset(name: "map_pin_single_no_mobile_order_disabled")
    public static let statedefaultMobileOrderfalseThemedefault = ImageAsset(name: "statedefault_mobile_orderfalse_themedefault")
    public static let statedefaultMobileOrdertrueThemedefault = ImageAsset(name: "statedefault_mobile_ordertrue_themedefault")
    public static let statedefaultMobileOrdertrueThemeeuropeGreen = ImageAsset(name: "statedefault_mobile_ordertrue_themeeurope_green")
    public static let statedisabledMobileOrderfalseThemedefault = ImageAsset(name: "statedisabled_mobile_orderfalse_themedefault")
    public static let statedisabledMobileOrdertrueThemedefault = ImageAsset(name: "statedisabled_mobile_ordertrue_themedefault")
    public static let statedisabledMobileOrdertrueThemeeuropeGreen = ImageAsset(name: "statedisabled_mobile_ordertrue_themeeurope_green")
  }
  public enum StatusIcons {
    public static let deprecatedIcStatusAlert12Old = ImageAsset(name: "deprecated_ic_status_alert_12_old")
    public static let deprecatedIcStatusAlert16Old = ImageAsset(name: "deprecated_ic_status_alert_16_old")
    public static let deprecatedIcStatusAlert20Old = ImageAsset(name: "deprecated_ic_status_alert_20_old")
    public static let icAlertDefault32 = ImageAsset(name: "ic_alert_default_32")
    public static let icAlertFilled32 = ImageAsset(name: "ic_alert_filled_32")
    public static let icBlockerDefault32 = ImageAsset(name: "ic_blocker_default_32")
    public static let icBlockerFilled32 = ImageAsset(name: "ic_blocker_filled_32")
    public static let icStatusAlert12 = ImageAsset(name: "ic_status_alert_12")
    public static let icStatusAlert16 = ImageAsset(name: "ic_status_alert_16")
    public static let icStatusAlert20 = ImageAsset(name: "ic_status_alert_20")
    public static let icStatusBlocker12 = ImageAsset(name: "ic_status_blocker_12")
    public static let icStatusBlocker16 = ImageAsset(name: "ic_status_blocker_16")
    public static let icStatusBlocker20 = ImageAsset(name: "ic_status_blocker_20")
    public static let icStatusCheck = ImageAsset(name: "ic_status_check")
    public static let icStatusFalse20v2 = ImageAsset(name: "ic_status_false_20v2")
    public static let icStatusInfo12 = ImageAsset(name: "ic_status_info_12")
    public static let icStatusInfo16 = ImageAsset(name: "ic_status_info_16")
    public static let icStatusInfo20 = ImageAsset(name: "ic_status_info_20")
    public static let icStatusSelected12 = ImageAsset(name: "ic_status_selected_12")
    public static let icStatusSelected16 = ImageAsset(name: "ic_status_selected_16")
    public static let icStatusSelected20 = ImageAsset(name: "ic_status_selected_20")
    public static let icStatusSuccess12 = ImageAsset(name: "ic_status_success_12")
    public static let icStatusSuccess16 = ImageAsset(name: "ic_status_success_16")
    public static let icStatusSuccess20 = ImageAsset(name: "ic_status_success_20")
  }
}
// swiftlint:enable identifier_name line_length nesting type_body_length type_name

// MARK: - Implementation Details

public struct ImageAsset {
  public fileprivate(set) var name: String

  #if os(macOS)
  public typealias Image = NSImage
  #elseif os(iOS) || os(tvOS) || os(watchOS)
  public typealias Image = UIImage
  #endif

  @available(iOS 8.0, tvOS 9.0, watchOS 2.0, macOS 10.7, *)
  public var image: Image {
    let bundle = Bundle.designAssets
    #if os(iOS) || os(tvOS)
    let image = Image(named: name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    let name = NSImage.Name(self.name)
    let image = (bundle == .main) ? NSImage(named: name) : bundle.image(forResource: name)
    #elseif os(watchOS)
    let image = Image(named: name)
    #endif
    guard let result = image else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }

  #if os(iOS) || os(tvOS)
  @available(iOS 8.0, tvOS 9.0, *)
  public func image(compatibleWith traitCollection: UITraitCollection) -> Image {
    let bundle = Bundle.designAssets
    guard let result = Image(named: name, in: bundle, compatibleWith: traitCollection) else {
      fatalError("Unable to load image asset named \(name).")
    }
    return result
  }
  #endif

  #if canImport(SwiftUI)
  @available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
  public var swiftUIImage: SwiftUI.Image {
    SwiftUI.Image(asset: self)
  }
  #endif
}

public extension ImageAsset.Image {
  @available(iOS 8.0, tvOS 9.0, watchOS 2.0, *)
  @available(macOS, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init?(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = Bundle.designAssets
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(macOS)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

#if canImport(SwiftUI)
@available(iOS 13.0, tvOS 13.0, watchOS 6.0, macOS 10.15, *)
public extension SwiftUI.Image {
  init(asset: ImageAsset) {
    let bundle = Bundle.designAssets
    self.init(asset.name, bundle: bundle)
  }

  init(asset: ImageAsset, label: Text) {
    let bundle = Bundle.designAssets
    self.init(asset.name, bundle: bundle, label: label)
  }

  init(decorative asset: ImageAsset) {
    let bundle = Bundle.designAssets
    self.init(decorative: asset.name, bundle: bundle)
  }
}
#endif
