// Generated by DesignAssets Figma Integration
// Do not edit this file manually
// Generated on: 2025-09-25 13:43:24 +0000

import Foundation
#if canImport(SwiftUI)
import SwiftUI
#endif
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Generated Icons

public struct GeneratedIcons {
    public static let bundle = Bundle.module
    
    // MARK: - Icon Access
    
    @available(iOS 13.0, macOS 10.15, *)
    public static func icon(named name: String) -> Image? {
        #if canImport(SwiftUI)
        return Image(name, bundle: bundle)
        #else
        return nil
        #endif
    }
    
    public static func uiImage(named name: String) -> Any? {
        #if canImport(UIKit)
        return UIImage(named: name, in: bundle, compatibleWith: nil)
        #else
        return nil
        #endif
    }
}

// MARK: - Icon Categories

public extension GeneratedIcons {
    enum General: String, CaseIterable {
    case home_icon = "home_icon"
    case search_icon = "search_icon"
        @available(iOS 13.0, macOS 10.15, *)
        public var image: Image? {
            return GeneratedIcons.icon(named: self.rawValue)
        }
        
        public var uiImage: Any? {
            return GeneratedIcons.uiImage(named: self.rawValue)
        }
    }
}

public extension GeneratedIcons {
    enum Map: String, CaseIterable {
    case location_pin = "location_pin"
        @available(iOS 13.0, macOS 10.15, *)
        public var image: Image? {
            return GeneratedIcons.icon(named: self.rawValue)
        }
        
        public var uiImage: Any? {
            return GeneratedIcons.uiImage(named: self.rawValue)
        }
    }
}

public extension GeneratedIcons {
    enum Status: String, CaseIterable {
    case success_icon = "success_icon"
        @available(iOS 13.0, macOS 10.15, *)
        public var image: Image? {
            return GeneratedIcons.icon(named: self.rawValue)
        }
        
        public var uiImage: Any? {
            return GeneratedIcons.uiImage(named: self.rawValue)
        }
    }
}

// MARK: - All Icons

public extension GeneratedIcons {
    enum All: String, CaseIterable {
    case home_icon = "home_icon"
    case location_pin = "location_pin"
    case search_icon = "search_icon"
    case success_icon = "success_icon"
        @available(iOS 13.0, macOS 10.15, *)
        public var image: Image? {
            return GeneratedIcons.icon(named: self.rawValue)
        }
        
        public var uiImage: Any? {
            return GeneratedIcons.uiImage(named: self.rawValue)
        }
        
        public var category: String {
            switch self {
case .home_icon:
    return "General"
case .search_icon:
    return "General"
case .success_icon:
    return "Status"
case .location_pin:
    return "Map"
            }
        }
    }
}